services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./php/src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  # mysql
  db:
    image: mysql:8.0
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: linkedin

volumes:
  mysqldata:
